package com.app.entities;

public enum TypeOfCase {
	MISSING_OR_STOLEN_MOBILE_PHONES,MISSING_CHILD_OR_PERSON, MOTOR_VEHICLE_THEFT,
	DACIOTY_OR_ROBBERY_OR_BURGLARY, RAPE, INSULT_TO_MODESTY_OF_WOMEN,
	DOWRY_DEATH, DOWRY_DEMAND, FORCED_PROSTITUTION, DOMESTIC_VIOLENCE, TRAFFICKING_OF_WOMEN, ACID_ATTACK,
	KIDNAPPING,CHILD_LABOUR, ASSAULT_ON_CHILDREN, SELLING_MINORS_FOR_PROSTITUTION, SLAVERY,
	SUSPICIOUS_OBJECT_FOUND, FATAL_ACCIDENT,SIMPLE_ACCIDENT, CHEATING,CHAIN_SNATCHING,
	MURDER, ATTEMPT_TO_MURDER, SUICIDE,UNIDENTIFIED_CHILD_OR_PERSON_OR_DEADBODY_FOUND,
	THEFT, TREE_CUTTING, OTHER;
}
