package com.app.entities;

public enum VehicleType {
	AMBULANCE, BUS, CAR, EARTH_MOVER, EXCAVATOR, JEEP, LORRY, METADOR, ROAD_ROLLER, STATION_WAGON, VAN, TAXI, TEMPO,
	THREE_WHEELER, TRACTOR, TRAILOR, TRUCK, TWO_WHEELER, UNKNOWN;
}
